# https://Taskfile.dev

version: 3

silent: true

vars:
  fuseki_version: "5.5.0-0"
  prez_version: "4.23.4"
  prezui_version: "4.2.0"
  kurra_version: "2.0.4"

tasks:
  install:prez-ui:
    cmds:
      - echo "Creating new Prez-UI app in ./prez-ui"
      - pnpm dlx create-prez-app@{{.prezui_version}} prez-ui
      - echo "Installing prez-ui dependencies"
      - pnpm install --prefix prez-ui
    status:
      - test -d prez-ui

  build:prez-ui:
    dir: prez-ui
    cmds:
      - echo "Generating prez-ui static files"
      - pnpm generate
    status:
      - test -f dist/index.html

  dev:up:
    cmds:
      - echo "Standing up the compose stack"
      - FUSEKI_VERSION={{.fuseki_version}} PREZ_VERSION={{.prez_version}} docker compose -f docker/compose.yml up -d

  dev:down:
    cmds:
      - echo "Taking down the compose stack"
      - FUSEKI_VERSION={{.fuseki_version}} PREZ_VERSION={{.prez_version}} docker compose -f docker/compose.yml down

  dev:restart:
    cmds:
      - FUSEKI_VERSION={{.fuseki_version}} PREZ_VERSION={{.prez_version}} docker compose -f docker/compose.yml restart

  dev:load:
    cmds:
      - echo "Loading data to fuseki from the ./data folder"
      - uvx kurra@{{.kurra_version}} db gsp post data http://localhost:3030/demods -g https://graphs/prezdemo

  dev:reload:
    cmds:
      - task: dev:restart
      - task: dev:load

  demo:start:
    cmds:
      - task: install:prez-ui
      - task: build:prez-ui
      - task: dev:up
      - task: dev:load
      - echo "Opening Prez-ui (http://localhost:3000/catalogs) in the default webrowser."
      - uv run python -m webbrowser -t 'http://localhost:3000/catalogs'

  demo:stop:
    cmds:
      - task: dev:down
